In [1]:
import numpy as np

In [5]:
a = np.array([[1,2,3,4],[200,100,300,1000]])

print(a)
a[0].mean()

[[   1    2    3    4]
 [ 200  100  300 1000]]


2.5

In [12]:
import numpy as np

# Original 2D array
arr = np.array([[1, 2], [3, 4]])

# Using ravel() (creates a view if possible)
ravel_arr = arr.ravel()
print(ravel_arr)
ravel_arr[0] = 99  # Modifies the original array since ravel may return a view

# Using flatten() (always returns a copy)
flatten_arr = arr.flatten()  
flatten_arr[0] = 100  # Does not modify the original array

print("Original array after ravel modification:", arr)  # Output: [[99  2] [ 3  4]]
print("Flattened copy remains unchanged:", flatten_arr)  # Output: [100   2   3   4]


[1 2 3 4]
Original array after ravel modification: [[99  2]
 [ 3  4]]
Flattened copy remains unchanged: [100   2   3   4]


In [ ]:
np.linspace(20,100,200)

# linspace will create number in the number of you want 
# like 200 number between 20 and 100

array([ 20.        ,  20.40201005,  20.8040201 ,  21.20603015,
        21.6080402 ,  22.01005025,  22.4120603 ,  22.81407035,
        23.2160804 ,  23.61809045,  24.0201005 ,  24.42211055,
        24.8241206 ,  25.22613065,  25.6281407 ,  26.03015075,
        26.4321608 ,  26.83417085,  27.2361809 ,  27.63819095,
        28.04020101,  28.44221106,  28.84422111,  29.24623116,
        29.64824121,  30.05025126,  30.45226131,  30.85427136,
        31.25628141,  31.65829146,  32.06030151,  32.46231156,
        32.86432161,  33.26633166,  33.66834171,  34.07035176,
        34.47236181,  34.87437186,  35.27638191,  35.67839196,
        36.08040201,  36.48241206,  36.88442211,  37.28643216,
        37.68844221,  38.09045226,  38.49246231,  38.89447236,
        39.29648241,  39.69849246,  40.10050251,  40.50251256,
        40.90452261,  41.30653266,  41.70854271,  42.11055276,
        42.51256281,  42.91457286,  43.31658291,  43.71859296,
        44.12060302,  44.52261307,  44.92462312,  45.32

In [22]:
np.zeros([2,4,4]).shape

(2, 4, 4)

In [27]:
a = np.array([100,10,20,22,40,500])

np.where(a>100, "arash", a)

array(['100', '10', '20', '22', '40', 'arash'], dtype='<U11')

In [4]:
import numpy as np
import os

# Your array
a = np.array([1, 2, 3], dtype = int)

# Define the path
path = 'data/aa.txt'

# Create directory if it doesn't exist
os.makedirs(os.path.dirname(path), exist_ok=True)

# Save the array
np.savetxt(path, a)

b =np.loadtxt('data/aa.txt', delimiter = ',')
print(b)
print(a)

[1. 2. 3.]
[1 2 3]


In [9]:
num1 =np.array([2,3,4])
num2 = np.array([23,24])
np.concatenate([num1, num2])

array([ 2,  3,  4, 23, 24])